---
- name: 'GIT : change global settings'
  community.general.git_config:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    scope: global
  loop:
    - { name: user.name, value: '{{ git_user }}' }
    - { name: user.email, value: '{{ git_email }}' }
    - { name: pull.rebase, value: 'true' }

- name: 'GIT : get local repo name'
  community.general.git_config:
    scope: local
    repo: .
    name: remote.origin.url
  register: output

- name: 'GIT : change local repo origin'
  community.general.git_config:
    scope: local
    repo: .
    name: remote.origin.url
    value: "{{ output.config_value | replace('https://github.com/','git@github.com:') }}"
