- name: 'GIT : change global settings'
  community.general.git_config:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    scope: global
  loop:
    - { name: user.name, value: '{{ git_user }}' }
    - { name: user.email, value: '{{ git_email }}' }
    - { name: pull.rebase, value: 'true' }
